version: '3.8'
services:
  crypto-analyst:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name : crypto-analyst
    ports:
      - "8000:8000"
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}